"""empty message

Revision ID: 338889fb93ee
Revises: f678c159dc24
Create Date: 2025-01-22 04:27:53.903208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338889fb93ee'
down_revision: Union[str, None] = 'f678c159dc24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_question voter_question_id_question')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_question voter_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'question_id', name=op.f('pk_question voter'))
    )
    op.create_table('comment_voter',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('fk_comment_voter_comment_id_comment')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_comment_voter_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'comment_id', name=op.f('pk_comment_voter'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_voter')
    op.drop_table('question voter')
    # ### end Alembic commands ###
