"""empty message

Revision ID: 8136f3614aab
Revises: cbfdf12c1d4c
Create Date: 2025-01-08 00:06:43.194133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8136f3614aab'
down_revision: Union[str, None] = 'cbfdf12c1d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('quest', sa.Text(), nullable=False))
    op.add_column('question', sa.Column('answer', sa.Text(), nullable=False))
    op.drop_column('question', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('content', sa.TEXT(), nullable=False))
    op.drop_column('question', 'answer')
    op.drop_column('question', 'quest')
    # ### end Alembic commands ###
